version: "3.9"
services:
  server:
    build: server
    container_name: server
    hostname: server
    init: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - internal

  client:
    build: client
    container_name: client
    hostname: client
    command: tail -f /dev/null
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - internal

networks:
  internal:
    driver: bridge
